In [35]:
import torch
import torch.nn as nn

max_sequence_length = 10
d_model = 6


In [36]:
even_i = torch.arange(0, d_model, 2).float()
odd_i = torch.arange(1, d_model, 2).float()

In [37]:
even_denominator = torch.pow(10000, even_i/d_model)
odd_denominator = torch.pow(10000, (odd_i-1)/d_model)

In [38]:
even_denominator

tensor([  1.0000,  21.5443, 464.1590])

In [39]:
denominator = even_denominator

In [40]:
position = torch.arange(max_sequence_length, dtype=torch.float).reshape(max_sequence_length, 1)

In [41]:
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [42]:
#position is of two types even position and odd position
odd_position = torch.sin(position/odd_denominator)
even_position = torch.cos(position/even_denominator)

In [43]:
odd_position.size

<function Tensor.size>

In [44]:
odd_position.shape

torch.Size([10, 3])

In [45]:
odd_position

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.8415,  0.0464,  0.0022],
        [ 0.9093,  0.0927,  0.0043],
        [ 0.1411,  0.1388,  0.0065],
        [-0.7568,  0.1846,  0.0086],
        [-0.9589,  0.2300,  0.0108],
        [-0.2794,  0.2749,  0.0129],
        [ 0.6570,  0.3192,  0.0151],
        [ 0.9894,  0.3629,  0.0172],
        [ 0.4121,  0.4057,  0.0194]])

In [46]:
even_position

tensor([[ 1.0000,  1.0000,  1.0000],
        [ 0.5403,  0.9989,  1.0000],
        [-0.4161,  0.9957,  1.0000],
        [-0.9900,  0.9903,  1.0000],
        [-0.6536,  0.9828,  1.0000],
        [ 0.2837,  0.9732,  0.9999],
        [ 0.9602,  0.9615,  0.9999],
        [ 0.7539,  0.9477,  0.9999],
        [-0.1455,  0.9318,  0.9999],
        [-0.9111,  0.9140,  0.9998]])

In [47]:
stack = torch.stack([even_position, odd_position], dim=1)

In [50]:
PE = torch.flatten(stack, start_dim=1, end_dim=2)
PE

tensor([[ 1.0000,  1.0000,  1.0000,  0.0000,  0.0000,  0.0000],
        [ 0.5403,  0.9989,  1.0000,  0.8415,  0.0464,  0.0022],
        [-0.4161,  0.9957,  1.0000,  0.9093,  0.0927,  0.0043],
        [-0.9900,  0.9903,  1.0000,  0.1411,  0.1388,  0.0065],
        [-0.6536,  0.9828,  1.0000, -0.7568,  0.1846,  0.0086],
        [ 0.2837,  0.9732,  0.9999, -0.9589,  0.2300,  0.0108],
        [ 0.9602,  0.9615,  0.9999, -0.2794,  0.2749,  0.0129],
        [ 0.7539,  0.9477,  0.9999,  0.6570,  0.3192,  0.0151],
        [-0.1455,  0.9318,  0.9999,  0.9894,  0.3629,  0.0172],
        [-0.9111,  0.9140,  0.9998,  0.4121,  0.4057,  0.0194]])


import torch
import torch.nn as nn

class PositionalEncoding(nn.Module):
    """
    Positional encoding module for transformer architectures.
    """

    def __init__(self, d_model, max_sequence_length):
        """
        Constructor method for PositionalEncoding class.

        Args:
            d_model (int): Dimensionality of the model.
            max_sequence_length (int): Maximum sequence length.
        """
        super().__init__()
        self.max_sequence_length = max_sequence_length
        self.d_model = d_model

    def forward(self):
        """
        Forward method to compute positional encoding.

        Returns:
            torch.Tensor: Positional encoding tensor.
        """
        # Calculate even indices
        even_i = torch.arange(0, self.d_model, 2).float()
        # Calculate denominators
        denominator = torch.pow(10000, even_i/self.d_model)
        # Create position tensor
        position = torch.arange(self.max_sequence_length).reshape(self.max_sequence_length, 1)
        # Calculate even positional encoding
        even_PE = torch.sin(position / denominator)
        # Calculate odd positional encoding
        odd_PE = torch.cos(position / denominator)
        # Stack even and odd encodings
        stacked = torch.stack([even_PE, odd_PE], dim=2)
        # Flatten the stacked tensor
        PE = torch.flatten(stacked, start_dim=1, end_dim=2)
        return PE

# Create an instance of PositionalEncoding
pe = PositionalEncoding(d_model=6, max_sequence_length=10)
# Compute positional encoding
pe.forward()





